module.exports = function () {
    return [
        'A Coruña',
        'Álava/Araba',
        'Albacete',
        'Alicante',
        'Almería',
        'Andorra',
        'Asturias',
        'Ávila',
        'Badajoz',
        'Baleares/Balears',
        'Barcelona',
        'Bilbao',
        'Burgos',
        'Cáceres',
        'Cádiz',
        'Cantabria',
        'Castellón',
        'Cerdanya Francesa',
        'Ceuta',
        'Ciudad Real',
        'Córdoba',
        'Cuenca',
        'Formentera-Ibiza',
        'Fuerteventura',
        'Gerona/Girona',
        'Gijón',
        'Gran Canaria',
        'Granada',
        'Guadalajara',
        'Guipúzcoa/Gipuzkoa',
        'Huelva',
        'Huesca',
        'Ibiza-Formentera',
        'Jaén',
        'La Palma (Isla)',
        'La Rioja',
        'Lanzarote',
        'Las Palmas',
        'Las Palmas de Gran Canaria',
        'León',
        'Lérida/Lleida',
        'Logroño',
        'Lugo',
        'Madrid',
        'Málaga',
        'Mallorca',
        'Melilla',
        'Menorca',
        'Mérida',
        'Murcia',
        'Navarra/Nafarroa',
        'Orense/Ourense',
        'Oviedo',
        'País Vasco Francés',
        'Palencia',
        'Palma de Mallorca',
        'Palmas de Gran Canaria (Las)',
        'Pamplona/Iruña',
        'Pontevedra',
        'Salamanca',
        'San Sebastián/Donostia',
        'Santa Cruz de Tenerife',
        'Santander',
        'Santiago de Compostela',
        'Segovia',
        'Sevilla',
        'Soria',
        'Tarragona',
        'Tenerife',
        'Teruel',
        'Toledo',
        'Valencia/València',
        'Valladolid',
        'Vitoria-Gasteiz',
        'Vizcaya/Bizkaia',
        'Zamora',
        'Zaragoza',
        'Andorra',
        'Italia',
        'Portugal',
    ];
}