export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT",
      START_CHAT = "START_CHAT",
      END_CHAT = "END_CHAT",
      SUBMIT_MESSAGE = "SUBMIT_MESSAGE",
      UPDATE_FILTER = "UPDATE_FILTER",
      SET_THEME = "SET_THEME",
      CHAT_ON = "CHAT_ON",
      CHAT_OFF = "CHAT_OFF",
      CHAT_UBI = "CHAT_UBI";
    
      